@startuml subroutine_subacute_or_chronic_pain
!theme carbon-gray
skinparam ActivityBackgroundColor #306516
<style>
activityDiagram {
 FontColor white
 RoundCorner 50
 arrow {
  FontColor: Black
 }
 diamond {
  BackgroundColor #306516
 }
}
</style>
title Subacute or Chronic Pain Subroutine
start
fork
:  Opioid analgesic order \n  with an expected supply \n    duration of 28 days\n         or longer?;
fork again
:Opioid analgesic order \n  in the past 90 days \n    with "continuous" \n      therapy type?;
fork again
:Opioid analgesic order \n for 28 of the past 90 \n days (including today)?;
-> AND;
:    Active or pending \nopioid analgesic order?;
end merge
if (Any answer is yes?) then (yes)
#BC2C73:Return Yes;
kill
else (no)
#BC2C73:Return No;
kill
@enduml